"""create company table with relation to user

Revision ID: 37f7c18703a3
Revises: f16f67da7dea
Create Date: 2024-01-09 21:34:01.601795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f7c18703a3'
down_revision: Union[str, None] = 'f16f67da7dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_owner_id'), 'company', ['owner_id'], unique=True)
    op.add_column('users', sa.Column('player_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_player_name'), 'users', ['player_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_player_name'), table_name='users')
    op.drop_column('users', 'player_name')
    op.drop_index(op.f('ix_company_owner_id'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
